# Generated by Django 4.0.2 on 2023-11-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='insert description here.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
